package com.alchemistdigital.buxa.utilities;

import java.util.ArrayList;

/**
 * Created by user on 10/12/2016.
 */
public class InternationalDestinationPorts {
    private ArrayList<String> portsName = new ArrayList<>();
    private ArrayList<String> portsCountry = new ArrayList<>();

    /**
     * value : Destination
     * @return portsName
     */
    public ArrayList getPortName() {

        // Destinations
        portsName.add("AARHUS");
        portsName.add("ABIDJAN");
        portsName.add("ABU DHABI");
        portsName.add("ACAJUTLA");
        portsName.add("ACCRA");
        portsName.add("ADANA");
        portsName.add("ADELAIDE");
        portsName.add("ADEN");
        portsName.add("AGRIGENTO");
        portsName.add("AGUASCALIENTES");
        portsName.add("AL SOKHNA");
        portsName.add("ALBACETE");
        portsName.add("ALBUQUERQUE");
        portsName.add("ALESSANDRIA");
        portsName.add("ALEXANDRIA");
        portsName.add("ALGECIRAS");
        portsName.add("ALGER");
        portsName.add("ALICANTE");
        portsName.add("ALMERIA");
        portsName.add("ALTAMIRA");
        portsName.add("AMBARLI");
        portsName.add("ANCONA");
        portsName.add("ANGUILLA ");
        portsName.add("ANKARA");
        portsName.add("ANQING");
        portsName.add("ANTANSNSTIVO");
        portsName.add("ANTIGUA");
        portsName.add("ANTOFAGASTA");
        portsName.add("ANTWERP");
        portsName.add("AOSTA");
        portsName.add("AQABA");
        portsName.add("AREMEINA");
        portsName.add("AREZZO");
        portsName.add("ARICA");
        portsName.add("ARUBA ");
        portsName.add("ARRECIFE");
        portsName.add("ASCOLI PICENO");
        portsName.add("ASHDOD");
        portsName.add("ASTI");
        portsName.add("ASUNCION");
        portsName.add("ATHENS");
        portsName.add("ATLANTA");
        portsName.add("AUCKLAND");
        portsName.add("AUGSBURG");
        portsName.add("AUSTIN");
        portsName.add("AVELLINO");
        portsName.add("AVILA");
        portsName.add("AZORES");
        portsName.add("BADAJOZ");
        portsName.add("BAHRAIN");
        portsName.add("BANJUL");
        portsName.add("BALBAO");
        portsName.add("BALTIMORE");
        portsName.add("BANDAR ABBAS");
        portsName.add("BANGKOK");
        portsName.add("BARCELONA");
        portsName.add("BARI");
        portsName.add("BARRANQUILLA");
        portsName.add("BASEL");
        portsName.add("BASSETERRE");
        portsName.add("BATAM");
        portsName.add("BATH");
        portsName.add("BEIJING");
        portsName.add("BEIRUT");
        portsName.add("BELAWAN");
        portsName.add("BELGRADE");
        portsName.add("BELIZE CITY");
        portsName.add("BELLUNO");
        portsName.add("BENEVENTO");
        portsName.add("BERGAMO");
        portsName.add("BERGEN");
        portsName.add("BERLIN");
        portsName.add("BERN");
        portsName.add("BIELEFELD");
        portsName.add("BIELLA");
        portsName.add("BILBAO");
        portsName.add("BINTULU");
        portsName.add("BIRMINGHAM");
        portsName.add("BIRMINGHAM");
        portsName.add("BLACKBURN");
        portsName.add("BLACKPOOL");
        portsName.add("BLANTYRE");
        portsName.add("BOGOTA");
        portsName.add("BOLOGNA");
        portsName.add("BOLTON");
        portsName.add("BOLZANO");
        portsName.add("BONN / HENNEF");
        portsName.add("BORDEAUX");
        portsName.add("BOSTON");
        portsName.add("BOTTROP");
        portsName.add("BOURNEMOUTH");
        portsName.add("BRADFORD");
        portsName.add("BRATISLAVA");
        portsName.add("BREMEN");
        portsName.add("BRESCIA");
        portsName.add("BREST");
        portsName.add("BRIDGETOWN");
        portsName.add("BRIGHTON");
        portsName.add("BRINDISI");
        portsName.add("BRISBANE");
        portsName.add("BRISTOL");
        portsName.add("BROWNSVILLE");
        portsName.add("BRUSSELS");
        portsName.add("BUCHAREST");
        portsName.add("BUDAPEST");
        portsName.add("BUENAVENTURA");
        portsName.add("BUENOS AIRES");
        portsName.add("BUFFALO");
        portsName.add("BUJUMBURA");
        portsName.add("BUKAVU");
        portsName.add("BUNIA");
        portsName.add("BURGOS");
        portsName.add("BURSA");
        portsName.add("BUSAN");
        portsName.add("BUTEMBO");
        portsName.add("CACERES");
        portsName.add("CADIZ");
        portsName.add("CAGLIARI");
        portsName.add("CAIRO");
        portsName.add("CALGARY");
        portsName.add("CALI");
        portsName.add("CALLAO");
        portsName.add("CALTANISSETTA");
        portsName.add("CAMBRIDGE");
        portsName.add("CAMPOBASSO");
        portsName.add("CANCUN");
        portsName.add("CANTERBURY");
        portsName.add("CAPE TOWN");
        portsName.add("CARACAS");
        portsName.add("CARDIFF");
        portsName.add("CARLISLE");
        portsName.add("CARTAGENA");
        portsName.add("CASABLANCA");
        portsName.add("CASERTA");
        portsName.add("CASTELLON");
        portsName.add("CASTRIES");
        portsName.add("CATANIA");
        portsName.add("CATANZARO");
        portsName.add("CAYENNE");
        portsName.add("CEBU");
        portsName.add("CELAYA");
        portsName.add("CESENA");
        portsName.add("CHANGSHU");
        portsName.add("CHANGZHOU");
        portsName.add("CHARLESTON");
        portsName.add("CHARLOTTE");
        portsName.add("CHATTANOOGA");
        portsName.add("CHELMSFORD");
        portsName.add("CHENGDU");
        portsName.add("CHESTER");
        portsName.add("CHICAGO");
        portsName.add("CHIETI");
        portsName.add("CHITTAGONG");
        portsName.add("CHONGQING");
        portsName.add("CHRISTCHURCH");
        portsName.add("CINCINNATI");
        portsName.add("CIUDAD");
        portsName.add("CIUDAD REAL");
        portsName.add("CIVITAVECCHIA");
        portsName.add("CLERMONT-FERRAND");
        portsName.add("CLEVELAND");
        portsName.add("CLEVELAND");
        portsName.add("COCHABAMBA");
        portsName.add("COCO SOLO");
        portsName.add("COLCHESTER");
        portsName.add("COLOGNE (KOLN)");
        portsName.add("COLOMBO");
        portsName.add("COLON FREE ZONE");
        portsName.add("COLUMBUS");
        portsName.add("COMO");
        portsName.add("CONAKARY");
        portsName.add("COPENHAGEN");
        portsName.add("CORDOBA");
        portsName.add("CORINTO");
        portsName.add("COSENZA");
        portsName.add("COSLADA");
        portsName.add("COTONOU");
        portsName.add("COVENTRY");
        portsName.add("CRAKOW");
        portsName.add("CREMONA");
        portsName.add("CREWE");
        portsName.add("CRISTOBAL");
        portsName.add("CUENCA");
        portsName.add("CUENZA");
        portsName.add("CUNEO");
        portsName.add("CUERNAVACA");
        portsName.add("CURITIBA");
        portsName.add("DAKAR");
        portsName.add("DALIAN");
        portsName.add("DALLAS");
        portsName.add("DAMIETTA");
        portsName.add("DAMMAM");
        portsName.add("DAR ES SALAAM");
        portsName.add("DARLINGTON");
        portsName.add("DAYTON");
        portsName.add("DENVER");
        portsName.add("DERBY");
        portsName.add("DES MOINES");
        portsName.add("DETROIT CITY");
        portsName.add("DHAKA");
        portsName.add("DIJON");
        portsName.add("DJIBOUTI");
        portsName.add("DOHA");
        portsName.add("DORCHESTER");
        portsName.add("DORTMUND");
        portsName.add("DOUALA");
        portsName.add("DRESDEN");
        portsName.add("DUBAI");
        portsName.add("DUBLIN");
        portsName.add("DUDLEY");
        portsName.add("DUESSELDORF");
        portsName.add("DUNEDIN");
        portsName.add("DURBAN");
        portsName.add("DURHAM");
        portsName.add("EAST LONDON");
        portsName.add("EDMONTON");
        portsName.add("EL GUAMACHE");
        portsName.add("EL PASO");
        portsName.add("ENNA");
        portsName.add("ENTEBBE");
        portsName.add("ESBJERG");
        portsName.add("ESSEN");
        portsName.add("EXETER");
        portsName.add("FELIXSTOWE");
        portsName.add("FERRARA");
        portsName.add("FIRENZE (FLORENCE)");
        portsName.add("FOGGIA");
        portsName.add("FORLI");
        portsName.add("FORT DE FRANCE");
        portsName.add("FORTALEZA");
        portsName.add("FOSHAN");
        portsName.add("FRANKFURT");
        portsName.add("FREEPORT");
        portsName.add("FREETOWN");
        portsName.add("FREIBURG");
        portsName.add("FREMANTLE");
        portsName.add("FROSINONE");
        portsName.add("FUKUYAMA");
        portsName.add("FUNKAL");
        portsName.add("FUZHOU (MAIWEI)");
        portsName.add("GABORONE");
        portsName.add("GAOMING");
        portsName.add("GDANSK");
        portsName.add("GDYNIA");
        portsName.add("GEBZE");
        portsName.add("GELSENKIRCHEN");
        portsName.add("GEMLIK");
        portsName.add("GENERAL SANTOS");
        portsName.add("GENEVA");
        portsName.add("GENOA");
        portsName.add("GEORGETOWN, GY");
        portsName.add("GEORGETOWN, JM");
        portsName.add("GIESSEN");
        portsName.add("GLOUCESTER");
        portsName.add("GOMA");
        portsName.add("GORIZIA");
        portsName.add("GOTHENBURG");
        portsName.add("GRANADA");
        portsName.add("GRAND CAYMAN");
        portsName.add("GRAND RAPIDS");
        portsName.add("GRAZ");
        portsName.add("GREENSBORO");
        portsName.add("GREENVILLE");
        portsName.add("GRENOBLE");
        portsName.add("GROSSETO");
        portsName.add("GUALDAJARA");
        portsName.add("GUANAJUATO");
        portsName.add("GUANGZHOU");
        portsName.add("GUATEMALA CITY");
        portsName.add("GUAYAQUIL");
        portsName.add("HAIKOU");
        portsName.add("HAIPHONG");
        portsName.add("HAKATA");
        portsName.add("HALIFAX");
        portsName.add("HALIFAX");
        portsName.add("HAMILTON");
        portsName.add("HAMBURG");
        portsName.add("HANGZHOU");
        portsName.add("HANNOVER");
        portsName.add("HANOI");
        portsName.add("HARARE");
        portsName.add("HARROGATE");
        portsName.add("HASTINGS");
        portsName.add("HEFEI");
        portsName.add("HELSINGBORG");
        portsName.add("HELSINKI");
        portsName.add("HEREFORD");
        portsName.add("HESHAN");
        portsName.add("HIDALGO");
        portsName.add("HIROSHIMA");
        portsName.add("HO CHI MINH CITY");
        portsName.add("HODEIDAH");
        portsName.add("HONG KONG");
        portsName.add("HORTA/ FAILAL");
        portsName.add("HOUSTON");
        portsName.add("HUADU");
        portsName.add("HUANGPU");
        portsName.add("HUDDERSFIELD");
        portsName.add("HUESCA");
        portsName.add("HUIZHOU");
        portsName.add("HULL");
        portsName.add("HUNTSVILLE, AL");
        portsName.add("IBIZA");
        portsName.add("ILIGAN");
        portsName.add("ILO ILO CITY");
        portsName.add("IMPERIA");
        portsName.add("INCHON");
        portsName.add("INDIANAPOLIS");
        portsName.add("IPSWICH");
        portsName.add("IQUIQUE");
        portsName.add("IRAPUATO");
        portsName.add("IRUN");
        portsName.add("ISERNIA");
        portsName.add("ISKENDERUN");
        portsName.add("ISTANBUL");
        portsName.add("ITAJAI");
        portsName.add("IZMIR");
        portsName.add("IZMIT");
        portsName.add("JACKSONVILLE");
        portsName.add("JAEN");
        portsName.add("JAKARTA");
        portsName.add("JEDDAH");
        portsName.add("JIANGMEN");
        portsName.add("JIANGYIN");
        portsName.add("JIAXING");
        portsName.add("JINGHAI COUNTY");
        portsName.add("JINJA");
        portsName.add("JIUJIANG");
        portsName.add("JOHANNESBURG");
        portsName.add("JOJ");
        portsName.add("KAMPALA");
        portsName.add("KANAZAWA");
        portsName.add("KANSAS CITY");
        portsName.add("KAOHSIUNG");
        portsName.add("KARACHI");
        portsName.add("KARLSRUHE");
        portsName.add("KASSEL");
        portsName.add("KAUNAS");
        portsName.add("KAYSERI");
        portsName.add("KEELUNG");
        portsName.add("KIEL");
        portsName.add("KIEV");
        portsName.add("KIGALI");
        portsName.add("KINGSHILL");
        portsName.add("KINGSTON");
        portsName.add("KINGSTOWN");
        portsName.add("KLAIPEDA");
        portsName.add("KNOXVILLE");
        portsName.add("KOBE");
        portsName.add("KOPER");
        portsName.add("KOTA KINABALU");
        portsName.add("KOTKA");
        portsName.add("KRALENDIJK");
        portsName.add("KUCHING");
        portsName.add("KUMAMOTO");
        portsName.add("KUNMING");
        portsName.add("KUNSHAN");
        portsName.add("KUWAIT");
        portsName.add("LA CHAUX D.F");
        portsName.add("LA CORUNA");
        portsName.add("LA GUAIRA");
        portsName.add("LA HAVANA");
        portsName.add("LA PAZ");
        portsName.add("LA VALETTA");
        portsName.add("LABUAN");
        portsName.add("LAE");
        portsName.add("LAEM CHABANG");
        portsName.add("LAGOS");
        portsName.add("LANCASTER");
        portsName.add("LANDSHUT");
        portsName.add("L'AQUILA");
        portsName.add("LAREDO");
        portsName.add("LAS MINAS");
        portsName.add("LAS PALMAS");
        portsName.add("LAS PALMAS");
        portsName.add("LAS VEGAS");
        portsName.add("LASPEZIA");
        portsName.add("LAT KRABANG");
        portsName.add("LATAKIA");
        portsName.add("LATINA");
        portsName.add("LAUSANNE");
        portsName.add("LAUTOKA");
        portsName.add("LE HAVRE");
        portsName.add("LE MANS");
        portsName.add("LECCE");
        portsName.add("LECCO");
        portsName.add("LEEDS");
        portsName.add("LEICESTER");
        portsName.add("LEIPZIG");
        portsName.add("LEIXOES");
        portsName.add("LEON");
        portsName.add("LEON");
        portsName.add("LIANHUASHAN");
        portsName.add("LIANYUNGANG");
        portsName.add("LIBREVILLE");
        portsName.add("LILLE");
        portsName.add("LIMA");
        portsName.add("LIMASSOL");
        portsName.add("LINCOLN");
        portsName.add("LINZ");
        portsName.add("LISBON");
        portsName.add("LITTLE ROCK");
        portsName.add("LIVERPOOL");
        portsName.add("LIVORNO");
        portsName.add("LJUBLJANA");
        portsName.add("LOGRONO");
        portsName.add("LOME");
        portsName.add("LONDON");
        portsName.add("LOS ANGELES");
        portsName.add("LOUISVILLE");
        portsName.add("LUANDA");
        portsName.add("LUCCA");
        portsName.add("LUDWIGSBURG");
        portsName.add("LUGO");
        portsName.add("LUSAKA");
        portsName.add("LUXEMBOURG");
        portsName.add("LYON");
        portsName.add("LYTTLETON");
        portsName.add("MACAU");
        portsName.add("MACERATA");
        portsName.add("MADEIRA");
        portsName.add("MADRID");
        portsName.add("MAGDEBURG");
        portsName.add("MAHE");
        portsName.add("MAIZURU");
        portsName.add("MALAGA");
        portsName.add("MALE");
        portsName.add("MALMO");
        portsName.add("MANAUS");
        portsName.add("MANAGUA");
        portsName.add("MANCHESTER");
        portsName.add("MANILA");
        portsName.add("MANIZALES");
        portsName.add("MANNHEIM");
        portsName.add("MANTOVA");
        portsName.add("MANZANILLO");
        portsName.add("MANZANILLO");
        portsName.add("MAPUTO");
        portsName.add("MARACAIBO");
        portsName.add("MARSEILLE");
        portsName.add("MASERU");
        portsName.add("MASSA CARRARA");
        portsName.add("MATAMOROS");
        portsName.add("MATADI");
        portsName.add("MATARANI");
        portsName.add("MATERA");
        portsName.add("MBALA");
        portsName.add("MEDELLIN");
        portsName.add("MELBOURNE");
        portsName.add("MEMPHIS");
        portsName.add("MERIDA");
        portsName.add("MERSIN");
        portsName.add("MESSINA");
        portsName.add("METZ");
        portsName.add("MEXICO CITY");
        portsName.add("MEXICO D.F.");
        portsName.add("MIAMI");
        portsName.add("MIDDLESBROUGH");
        portsName.add("MILANO");
        portsName.add("MILTON KEYNES");
        portsName.add("MILWAUKEE");
        portsName.add("MINNEAPOLIS");
        portsName.add("MINSK");
        portsName.add("MIRI");
        portsName.add("MOBILE");
        portsName.add("MODENA");
        portsName.add("MOJI");
        portsName.add("MOMBASA");
        portsName.add("MONCTON");
        portsName.add("MONROVIA");
        portsName.add("MONTEGO BAY");
        portsName.add("MONTERREY");
        portsName.add("MONTEVIDEO");
        portsName.add("MONTREAL");
        portsName.add("MOSCOW");
        portsName.add("MUARA");
        portsName.add("MUNICH (MUENCHEN)");
        portsName.add("MURCIA");
        portsName.add("MUSCAT(PORT SULTAN QABOOS)");
        portsName.add("NAGOYA");
        portsName.add("NAIROBI");
        portsName.add("NANHAI");
        portsName.add("NANJING");
        portsName.add("NANSHA");
        portsName.add("NANTES");
        portsName.add("NANTONG");
        portsName.add("NANTONG (JIANGSU)");
        portsName.add("NAOETSU");
        portsName.add("NAPIER");
        portsName.add("NAPOLI");
        portsName.add("NASHVILLE");
        portsName.add("NASSAU");
        portsName.add("NATAL");
        portsName.add("NELSON");
        portsName.add("NEUSS");
        portsName.add("NEW ORLEANS");
        portsName.add("NEW PLYMOUTH");
        portsName.add("NEW YORK");
        portsName.add("NEWCASTLE");
        portsName.add("NEWPORT");
        portsName.add("NEWIS");
        portsName.add("NICE / MONACO");
        portsName.add("NIIGATA");
        portsName.add("NINGBO");
        portsName.add("NOGALES");
        portsName.add("NORFOLK");
        portsName.add("NORRKOPING");
        portsName.add("NORTHAMPTON");
        portsName.add("NORWICH");
        portsName.add("NOTTINGHAM");
        portsName.add("NOUAKCHOTT");
        portsName.add("NOVARA");
        portsName.add("NUEVO LAREDO");
        portsName.add("NUORO");
        portsName.add("NURENBURG");
        portsName.add("OAKLAND");
        portsName.add("ODENSE");
        portsName.add("ODESSA");
        portsName.add("OFFENBACH");
        portsName.add("OKINAWA");
        portsName.add("OKLAHOMA CITY");
        portsName.add("OLDENBURG");
        portsName.add("OLDHAM");
        portsName.add("OMAHA");
        portsName.add("ORAN");
        portsName.add("ORANJESTAD");
        portsName.add("ORENSE");
        portsName.add("ORLANDO");
        portsName.add("OSAKA");
        portsName.add("OSLO");
        portsName.add("OTTAWA");
        portsName.add("OVIEDO");
        portsName.add("OXFORD");
        portsName.add("P. WESTFALICA");
        portsName.add("PACHUCA");
        portsName.add("PADOVA");
        portsName.add("PAITA");
        portsName.add("PALENCIA");
        portsName.add("PALERMO");
        portsName.add("PALMA MALL");
        portsName.add("PAMPLONA");
        portsName.add("PANAMA CITY");
        portsName.add("PAN-DONG");
        portsName.add("PAPEETE");
        portsName.add("PARAMARIBO");
        portsName.add("PARANAGUA");
        portsName.add("PARIS");
        portsName.add("PARMA");
        portsName.add("PASIR GUDANG");
        portsName.add("PAVIA");
        portsName.add("PENANG");
        portsName.add("PEREIRA");
        portsName.add("PERUGIA");
        portsName.add("PESARO");
        portsName.add("PESCARA");
        portsName.add("PETERBOROUGH");
        portsName.add("PHILADELPHIA");
        portsName.add("PHILIPSBURG");
        portsName.add("PHNOM PENH");
        portsName.add("PHOENIX");
        portsName.add("PIACENZA");
        portsName.add("PIRAEUS");
        portsName.add("PISA");
        portsName.add("PISCO");
        portsName.add("PISTOIA");
        portsName.add("PITTSBURG");
        portsName.add("PLYMOUTH");
        portsName.add("PLYMOUTH");
        portsName.add("POINT LISAS");
        portsName.add("POINTE NOIRE");
        portsName.add("POINTE A PITRE");
        portsName.add("PONTA DELGADA");
        portsName.add("PONTEVEDRA");
        portsName.add("PORDENONE");
        portsName.add("PORT AU PRINCE");
        portsName.add("PORT CHALMERS");
        portsName.add("PORT ELIZABETH");
        portsName.add("PORT HARTCOURT");
        portsName.add("PORT KELANG");
        portsName.add("PORT LOUIS");
        portsName.add("PORT MORESBY");
        portsName.add("PORT OF SPAIN");
        portsName.add("PORT SAID");
        portsName.add("PORT SUDAN");
        portsName.add("PORTLAND");
        portsName.add("PORTO");
        portsName.add("PORTO ALEGRE");
        portsName.add("PORTSMOUTH");
        portsName.add("PRAGUE");
        portsName.add("PRATO");
        portsName.add("PRAIA");
        portsName.add("PRESTON");
        portsName.add("PROGRESO");
        portsName.add("PUEBLA");
        portsName.add("PUERTO CABELLO");
        portsName.add("PUERTO CORTEZ");
        portsName.add("PUERTO DE ROSARIO");
        portsName.add("PUERTO LIMON");
        portsName.add("PUERTO MORELOS");
        portsName.add("PUERTO QUETZAL");
        portsName.add("PUERTO QUETZAL");
        portsName.add("PUERTO VALLARTA");
        portsName.add("PUNTA ARENAS");
        portsName.add("QINGDAO");
        portsName.add("QUEBEC CITY");
        portsName.add("QUERETARO");
        portsName.add("QUITO");
        portsName.add("RALEIGH");
        portsName.add("RAVENNA");
        portsName.add("RECIFE");
        portsName.add("REGENSBURG");
        portsName.add("REGGIO CALABRIA");
        portsName.add("REGGIO EMILIA");
        portsName.add("REGINA");
        portsName.add("REUNION");
        portsName.add("REYKJAVIK");
        portsName.add("REYNOSA");
        portsName.add("RHEINE");
        portsName.add("RICHMOND");
        portsName.add("RIESA");
        portsName.add("RIGA");
        portsName.add("RIJEKA");
        portsName.add("RIO DE JANEIRO");
        portsName.add("RIO GRANDE");
        portsName.add("RIO HAINA");
        portsName.add("RIYADH");
        portsName.add("ROAD TOWN");
        portsName.add("ROMA");
        portsName.add("RONGQI");
        portsName.add("ROSSEAU");
        portsName.add("ROSTOCK");
        portsName.add("ROTTERDAM");
        portsName.add("ROVIGO");
        portsName.add("SAARBRUECKEN");
        portsName.add("SAKAIMINATO");
        portsName.add("SAKATA");
        portsName.add("SALAMANCA");
        portsName.add("SALAVERRY");
        portsName.add("SALERNO");
        portsName.add("SALTILLO");
        portsName.add("SALT LAKE CITY");
        portsName.add("SALVADOR");
        portsName.add("SALZBURG");
        portsName.add("SAN ANTONIO");
        portsName.add("SAN ANTONIO");
        portsName.add("SAN DIEGO");
        portsName.add("SAN FRANCISCO");
        portsName.add("SAN JOSE");
        portsName.add("SAN JUAN");
        portsName.add("SAN LUIS DE POTOSI");
        portsName.add("SAN MIGUEL");
        portsName.add("SAN PEDRO SULA");
        portsName.add("SAN SALVADOR");
        portsName.add("SAN SEBASTIAN");
        portsName.add("SANSHAN");
        portsName.add("SANTA MARIA");
        portsName.add("SANTA MARTHA");
        portsName.add("SANTA CRUZ");
        portsName.add("SANTA CRUZ DE PALMA");
        portsName.add("SANTA DE TENERIFE");
        portsName.add("SANTANDER");
        portsName.add("SANTIAGO");
        portsName.add("SANTIAGO COM");
        portsName.add("SANTO DOMINGO");
        portsName.add("SANTO THOMAS DE CASTILLA");
        portsName.add("SANTOS");
        portsName.add("SAO PAULO");
        portsName.add("SARAJEWO");
        portsName.add("SASKATOON");
        portsName.add("SASSARI");
        portsName.add("SAVANNAH");
        portsName.add("SAVONA");
        portsName.add("SCHWEINFURT");
        portsName.add("SEATTLE");
        portsName.add("SEMARANG");
        portsName.add("SEOUL");
        portsName.add("SEVILLA");
        portsName.add("SFAX");
        portsName.add("SHANGHAI");
        portsName.add("SHANGYU");
        portsName.add("SHANTOU");
        portsName.add("SHAOXING");
        portsName.add("SHARJAH");
        portsName.add("SHEFFIELD");
        portsName.add("SHIMIZU");
        portsName.add("SHREVEPORT");
        portsName.add("SHREWSBURY");
        portsName.add("SIBU");
        portsName.add("SIENA");
        portsName.add("SIHANOUKVILLE");
        portsName.add("SINGAPORE");
        portsName.add("SIRACUSA");
        portsName.add("SIXTH OF OCTOBER CITY");
        portsName.add("SKOPJE");
        portsName.add("SLOUGH");
        portsName.add("SOFIA");
        portsName.add("SOLO");
        portsName.add("SONDRIO");
        portsName.add("SORIA");
        portsName.add("SOUSSE");
        portsName.add("SOUTHALL");
        portsName.add("SOUTHAMPTON");
        portsName.add("SPRINGFIELD");
        portsName.add("ST BARTHOLOME");
        portsName.add("ST CRUZ DES FLORES");
        portsName.add("ST GEORGE");
        portsName.add("ST JOHNS NB");
        portsName.add("ST LOUIS");
        portsName.add("ST. JOHN'S");
        portsName.add("ST. PETERSBURG");
        portsName.add("ST.THOMAS");
        portsName.add("STAVANGER");
        portsName.add("STOCKHOLM");
        portsName.add("STOCKPORT");
        portsName.add("STOKE");
        portsName.add("STRASBOURG");
        portsName.add("STUTTGART");
        portsName.add("SUAPE");
        portsName.add("SUEZ");
        portsName.add("SUNDERLAND");
        portsName.add("SURABAYA");
        portsName.add("SUVA");
        portsName.add("SUZHOU");
        portsName.add("SWANSEA");
        portsName.add("SWINDON");
        portsName.add("SYDNEY");
        portsName.add("TAICANG");
        portsName.add("TAICHUNG");
        portsName.add("TAIPING, DONGGUAN");
        portsName.add("TAKAMATSU");
        portsName.add("TAKORADI");
        portsName.add("TALCAHUANO");
        portsName.add("TALLINN");
        portsName.add("TAMATAVE");
        portsName.add("TAMPA");
        portsName.add("TAMPICO");
        portsName.add("TAMWORTH");
        portsName.add("TANGER");
        portsName.add("TARANTO");
        portsName.add("TAURANGA");
        portsName.add("TAWAU");
        portsName.add("TEGUCIGALPA");
        portsName.add("TELFORD");
        portsName.add("TEMA");
        portsName.add("TENERIFE");
        portsName.add("TENTH OF RAMADAN CITY");
        portsName.add("TERAMO");
        portsName.add("TERCIERA");
        portsName.add("TERNI");
        portsName.add("TERUEL");
        portsName.add("THESSALONIKI");
        portsName.add("THUNDER BAY");
        portsName.add("TIANJIN");
        portsName.add("TIMARU");
        portsName.add("TOAMASINA");
        portsName.add("TOKUSHIMA");
        portsName.add("TOKYO");
        portsName.add("TOLEDO");
        portsName.add("TOLEDO");
        portsName.add("TOLUCA");
        portsName.add("TOMAKOMAI");
        portsName.add("TORINO");
        portsName.add("TORONTO");
        portsName.add("TORQUAY");
        portsName.add("TORREON");
        portsName.add("TOULOSE");
        portsName.add("TOYAMA");
        portsName.add("TRENTO");
        portsName.add("TREVISO");
        portsName.add("TRIER");
        portsName.add("TRIESTE");
        portsName.add("TRIPOLI");
        portsName.add("TRONDHEIM");
        portsName.add("TRURO");
        portsName.add("TSURUGA");
        portsName.add("TUCSON");
        portsName.add("TULSA");
        portsName.add("TUMBES");
        portsName.add("TUNIS");
        portsName.add("TUNIS");
        portsName.add("TURKU");
        portsName.add("TUZLA");
        portsName.add("UDINE");
        portsName.add("ULM");
        portsName.add("VALENCIA");
        portsName.add("VALLADOLID");
        portsName.add("VALPARAISO");
        portsName.add("VANCOUVER");
        portsName.add("VARESE");
        portsName.add("VENEZIA");
        portsName.add("VENICE");
        portsName.add("VERACRUZ");
        portsName.add("VERCELLI");
        portsName.add("VERONA");
        portsName.add("VICENZA");
        portsName.add("VICTORIA");
        portsName.add("VICTORIA");
        portsName.add("VIENNA");
        portsName.add("VIGO");
        portsName.add("VILLENEUVE");
        portsName.add("VILLINGEN");
        portsName.add("VILNIUS");
        portsName.add("VITERBO");
        portsName.add("VITORIA");
        portsName.add("VUNGTAO");
        portsName.add("WAKEFIELD");
        portsName.add("WALSALL");
        portsName.add("WALVIS BAY");
        portsName.add("WARRINGTON");
        portsName.add("WARSAW");
        portsName.add("WASHINGTON");
        portsName.add("WATFORD");
        portsName.add("WELLINGTON");
        portsName.add("WENZHOU");
        portsName.add("WICHITA");
        portsName.add("WIGAN");
        portsName.add("WILLEMSTAD");
        portsName.add("WILMINGTON");
        portsName.add("WINDHOEK");
        portsName.add("WINNIPEG");
        portsName.add("WOLVERHAMPTON");
        portsName.add("WORCESTER");
        portsName.add("WUHAN");
        portsName.add("WUHU");
        portsName.add("WUPPERTAL");
        portsName.add("WUXI");
        portsName.add("XIAMEN");
        portsName.add("XINGANG");
        portsName.add("XINHUI");
        portsName.add("YANGON");
        portsName.add("YANGZHOU");
        portsName.add("YIXING");
        portsName.add("YOKOHAMA");
        portsName.add("YORK");
        portsName.add("YUYAO");
        portsName.add("ZAGREB");
        portsName.add("ZAMBOANGA");
        portsName.add("ZAMORA");
        portsName.add("ZARAGOZA");
        portsName.add("ZHANGJIAGANG");
        portsName.add("ZHENJIANG");
        portsName.add("ZHONGSHAN");
        portsName.add("ZHUHAI");
        portsName.add("ZURICH");

        return portsName;
    }

    public ArrayList getPortCountry() {

        // countries
        portsCountry.add("DENMARK");
        portsCountry.add("IVORY COAST");
        portsCountry.add("UAE");
        portsCountry.add("EL SALVADOR");
        portsCountry.add("GHANA");
        portsCountry.add("TURKEY");
        portsCountry.add("AUSTRALIA");
        portsCountry.add("YEMEN");
        portsCountry.add("ITALY");
        portsCountry.add("MEXICO");
        portsCountry.add("EGYPT");
        portsCountry.add("SPAIN");
        portsCountry.add("U.S.A");
        portsCountry.add("ITALY");
        portsCountry.add("EGYPT");
        portsCountry.add("SPAIN");
        portsCountry.add("ALGERIA");
        portsCountry.add("SPAIN");
        portsCountry.add("SPAIN");
        portsCountry.add("MEXICO");
        portsCountry.add("TURKEY");
        portsCountry.add("ITALY");
        portsCountry.add("CORINTO");
        portsCountry.add("TURKEY");
        portsCountry.add("CHINA");
        portsCountry.add("MADAGASCAR");
        portsCountry.add("W I ST JOHNS");
        portsCountry.add("CHILE");
        portsCountry.add("BELGIUM");
        portsCountry.add("ITALY");
        portsCountry.add("JORDAN");
        portsCountry.add("COLOMBIA");
        portsCountry.add("ITALY");
        portsCountry.add("CHILE");
        portsCountry.add("ORANJESTAD");
        portsCountry.add("CANARY ISLANDS");
        portsCountry.add("ITALY");
        portsCountry.add("ISRAEL");
        portsCountry.add("ITALY");
        portsCountry.add("PARAGUAY");
        portsCountry.add("GREECE");
        portsCountry.add("U.S.A");
        portsCountry.add("NEW ZEALAND");
        portsCountry.add("GERMANY");
        portsCountry.add("U.S.A");
        portsCountry.add("ITALY");
        portsCountry.add("SPAIN");
        portsCountry.add("PORTUGAL");
        portsCountry.add("SPAIN");
        portsCountry.add("BAHRAIN");
        portsCountry.add("GAMBIA");
        portsCountry.add("PANAMA");
        portsCountry.add("U.S.A");
        portsCountry.add("IRAN");
        portsCountry.add("THAILAND");
        portsCountry.add("SPAIN");
        portsCountry.add("ITALY");
        portsCountry.add("COLOMBIA");
        portsCountry.add("SWITZERLAND");
        portsCountry.add("ST KITTS-NEVIS");
        portsCountry.add("INDONESIA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("CHINA");
        portsCountry.add("LEBANON");
        portsCountry.add("INDONESIA");
        portsCountry.add("SERBIA ");
        portsCountry.add("BELIZE");
        portsCountry.add("ITALY");
        portsCountry.add("ITALY");
        portsCountry.add("ITALY");
        portsCountry.add("NORWAY");
        portsCountry.add("GERMANY");
        portsCountry.add("SWITZERLAND");
        portsCountry.add("GERMANY");
        portsCountry.add("ITALY");
        portsCountry.add("SPAIN");
        portsCountry.add("MALAYSIA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("U.S.A");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("MALAWI");
        portsCountry.add("COLOMBIA");
        portsCountry.add("ITALY");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("ITALY");
        portsCountry.add("GERMANY");
        portsCountry.add("FRANCE");
        portsCountry.add("U.S.A");
        portsCountry.add("GERMANY");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("SLOVAKIA");
        portsCountry.add("GERMANY");
        portsCountry.add("ITALY");
        portsCountry.add("FRANCE");
        portsCountry.add("BARBADOS");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("ITALY");
        portsCountry.add("AUSTRALIA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("U.S.A");
        portsCountry.add("BELGIUM");
        portsCountry.add("ROMANIA");
        portsCountry.add("HUNGARY");
        portsCountry.add("COLOMBIA");
        portsCountry.add("ARGENTINA");
        portsCountry.add("U.S.A");
        portsCountry.add("BURUNDI");
        portsCountry.add("REP DEMOCRATIQUE DU  CONGO");
        portsCountry.add("REP DEMOCRATIQUE DU  CONGO");
        portsCountry.add("SPAIN");
        portsCountry.add("TURKEY");
        portsCountry.add("SOUTH KOREA");
        portsCountry.add("REP DEMOCRATIQUE DU  CONGO");
        portsCountry.add("SPAIN");
        portsCountry.add("SPAIN");
        portsCountry.add("ITALY");
        portsCountry.add("EGYPT");
        portsCountry.add("CANADA");
        portsCountry.add("COLOMBIA");
        portsCountry.add("PERU");
        portsCountry.add("ITALY");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("ITALY");
        portsCountry.add("MEXICO");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("SOUTH AFRICA");
        portsCountry.add("VENEZUELA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("COLOMBIA");
        portsCountry.add("MOROCCO");
        portsCountry.add("ITALY");
        portsCountry.add("SPAIN");
        portsCountry.add("ST.LUCIA");
        portsCountry.add("ITALY");
        portsCountry.add("ITALY");
        portsCountry.add("FRENCH GUIANA");
        portsCountry.add("PHILIPPINES");
        portsCountry.add("MEXICO");
        portsCountry.add("ITALY");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("U.S.A");
        portsCountry.add("U.S.A");
        portsCountry.add("U.S.A");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("CHINA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("U.S.A");
        portsCountry.add("ITALY");
        portsCountry.add("BANGLADESH");
        portsCountry.add("CHINA");
        portsCountry.add("NEW ZEALAND");
        portsCountry.add("U.S.A");
        portsCountry.add("GUATEMALA");
        portsCountry.add("SPAIN");
        portsCountry.add("ITALY");
        portsCountry.add("FRANCE");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("U.S.A");
        portsCountry.add("BOLIVIA");
        portsCountry.add("PANAMA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("GERMANY");
        portsCountry.add("SRI LANKA");
        portsCountry.add("PANAMA");
        portsCountry.add("U.S.A");
        portsCountry.add("ITALY");
        portsCountry.add("GUINEA");
        portsCountry.add("DENMARK");
        portsCountry.add("SPAIN");
        portsCountry.add("NICARAGUA");
        portsCountry.add("ITALY");
        portsCountry.add("SPAIN");
        portsCountry.add("BENIN");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("POLAND");
        portsCountry.add("ITALY");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("PANAMA");
        portsCountry.add("SPAIN");
        portsCountry.add("ECUADOR");
        portsCountry.add("ITALY");
        portsCountry.add("MEXICO");
        portsCountry.add("BRAZIL");
        portsCountry.add("SENEGAL");
        portsCountry.add("CHINA");
        portsCountry.add("U.S.A");
        portsCountry.add("EGYPT");
        portsCountry.add("SAUDI ARABIA");
        portsCountry.add("TANZANIA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("U.S.A");
        portsCountry.add("U.S.A");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("U.S.A");
        portsCountry.add("U.S.A");
        portsCountry.add("BANGLADESH");
        portsCountry.add("FRANCE");
        portsCountry.add("DJIBOUTI");
        portsCountry.add("QATAR");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("GERMANY");
        portsCountry.add("CAMEROON");
        portsCountry.add("GERMANY");
        portsCountry.add("UAE");
        portsCountry.add("IRELAND");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("GERMANY");
        portsCountry.add("NEW ZEALAND");
        portsCountry.add("SOUTH AFRICA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("SOUTH AFRICA");
        portsCountry.add("CANADA");
        portsCountry.add("VENEZUELA");
        portsCountry.add("U.S.A");
        portsCountry.add("ITALY");
        portsCountry.add("UGANDA");
        portsCountry.add("DENMARK");
        portsCountry.add("GERMANY");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("ITALY");
        portsCountry.add("ITALY");
        portsCountry.add("ITALY");
        portsCountry.add("ITALY");
        portsCountry.add("MARTINIQUE");
        portsCountry.add("BRAZIL");
        portsCountry.add("CHINA");
        portsCountry.add("GERMANY");
        portsCountry.add("BAHAMAS");
        portsCountry.add("SIERRA LEONE");
        portsCountry.add("GERMANY");
        portsCountry.add("AUSTRALIA");
        portsCountry.add("ITALY");
        portsCountry.add("JAPAN");
        portsCountry.add("PORTUGAL");
        portsCountry.add("CHINA");
        portsCountry.add("BOTSWANA");
        portsCountry.add("CHINA");
        portsCountry.add("POLAND");
        portsCountry.add("POLAND");
        portsCountry.add("TURKEY");
        portsCountry.add("GERMANY");
        portsCountry.add("TURKEY");
        portsCountry.add("PHILIPPINES");
        portsCountry.add("SWITZERLAND");
        portsCountry.add("ITALY");
        portsCountry.add("GUYANA");
        portsCountry.add("JAMAICA");
        portsCountry.add("GERMANY");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("REP DEMOCRATIQUE DU  CONGO");
        portsCountry.add("ITALY");
        portsCountry.add("SWEDEN");
        portsCountry.add("SPAIN");
        portsCountry.add("CAYMAN ISLANDS");
        portsCountry.add("U.S.A");
        portsCountry.add("AUSTRIA");
        portsCountry.add("U.S.A");
        portsCountry.add("U.S.A");
        portsCountry.add("FRANCE");
        portsCountry.add("ITALY");
        portsCountry.add("MEXICO");
        portsCountry.add("MEXICO");
        portsCountry.add("CHINA");
        portsCountry.add("GUATEMALA");
        portsCountry.add("ECUADOR");
        portsCountry.add("CHINA");
        portsCountry.add("VIETNAM");
        portsCountry.add("JAPAN");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("CANADA");
        portsCountry.add("BERMUDA");
        portsCountry.add("GERMANY");
        portsCountry.add("CHINA");
        portsCountry.add("GERMANY");
        portsCountry.add("VIETNAM");
        portsCountry.add("ZIMBABWE");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("NEW ZEALAND");
        portsCountry.add("CHINA");
        portsCountry.add("SWEDEN");
        portsCountry.add("FINLAND");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("CHINA");
        portsCountry.add("U.S.A");
        portsCountry.add("JAPAN");
        portsCountry.add("VIETNAM");
        portsCountry.add("YEMEN");
        portsCountry.add("HONG KONG");
        portsCountry.add("PORTUGAL");
        portsCountry.add("U.S.A");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("SPAIN");
        portsCountry.add("CHINA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("U.S.A");
        portsCountry.add("SPAIN");
        portsCountry.add("PHILIPPINES");
        portsCountry.add("PHILIPPINES");
        portsCountry.add("ITALY");
        portsCountry.add("SOUTH KOREA");
        portsCountry.add("U.S.A");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("CHILE");
        portsCountry.add("MEXICO");
        portsCountry.add("SPAIN");
        portsCountry.add("ITALY");
        portsCountry.add("TURKEY");
        portsCountry.add("TURKEY");
        portsCountry.add("BRAZIL");
        portsCountry.add("TURKEY");
        portsCountry.add("TURKEY");
        portsCountry.add("U.S.A");
        portsCountry.add("SPAIN");
        portsCountry.add("INDONESIA");
        portsCountry.add("SAUDI ARABIA");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("UGANDA");
        portsCountry.add("CHINA");
        portsCountry.add("SOUTH AFRICA");
        portsCountry.add("INDONESIA");
        portsCountry.add("UGANDA");
        portsCountry.add("JAPAN");
        portsCountry.add("U.S.A");
        portsCountry.add("TAIWAN");
        portsCountry.add("PAKISTAN");
        portsCountry.add("GERMANY");
        portsCountry.add("GERMANY");
        portsCountry.add("LITHUANIA");
        portsCountry.add("TURKEY");
        portsCountry.add("TAIWAN");
        portsCountry.add("GERMANY");
        portsCountry.add("UKRAINE");
        portsCountry.add("RWANDA");
        portsCountry.add("ST. CROIX");
        portsCountry.add("JAMAICA");
        portsCountry.add("ST. VINCENT & GRENADINES");
        portsCountry.add("LITHUANIA");
        portsCountry.add("U.S.A");
        portsCountry.add("JAPAN");
        portsCountry.add("SLOVENIA");
        portsCountry.add("MALAYSIA");
        portsCountry.add("FINLAND");
        portsCountry.add("ANTILLES");
        portsCountry.add("MALAYSIA");
        portsCountry.add("JAPAN");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("KUWAIT");
        portsCountry.add("SWITZERLAND");
        portsCountry.add("SPAIN");
        portsCountry.add("VENEZUELA");
        portsCountry.add("CUBA");
        portsCountry.add("BOLIVIA");
        portsCountry.add("MALTA");
        portsCountry.add("MALAYSIA");
        portsCountry.add("PAPUA NEW GUINEA");
        portsCountry.add("THAILAND");
        portsCountry.add("NIGERIA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("GERMANY");
        portsCountry.add("ITALY");
        portsCountry.add("U.S.A");
        portsCountry.add("PANAMA");
        portsCountry.add("SPAIN");
        portsCountry.add("CANARY ISLANDS");
        portsCountry.add("U.S.A");
        portsCountry.add("ITALY");
        portsCountry.add("THAILAND");
        portsCountry.add("SYRIA");
        portsCountry.add("ITALY");
        portsCountry.add("SWITZERLAND");
        portsCountry.add("FIJI");
        portsCountry.add("FRANCE");
        portsCountry.add("FRANCE");
        portsCountry.add("ITALY");
        portsCountry.add("ITALY");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("GERMANY");
        portsCountry.add("PORTUGAL");
        portsCountry.add("SPAIN");
        portsCountry.add("MEXICO");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("GABON");
        portsCountry.add("FRANCE");
        portsCountry.add("PERU");
        portsCountry.add("CYPRUS");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("AUSTRIA");
        portsCountry.add("PORTUGAL");
        portsCountry.add("U.S.A");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("ITALY");
        portsCountry.add("SLOVENIA");
        portsCountry.add("SPAIN");
        portsCountry.add("TOGO");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("U.S.A");
        portsCountry.add("U.S.A");
        portsCountry.add("ANGOLA");
        portsCountry.add("ITALY");
        portsCountry.add("GERMANY");
        portsCountry.add("SPAIN");
        portsCountry.add("ZAMBIA");
        portsCountry.add("LUXEMBURG");
        portsCountry.add("FRANCE");
        portsCountry.add("NEW ZEALAND");
        portsCountry.add("CHINA");
        portsCountry.add("ITALY");
        portsCountry.add("PORTUGAL");
        portsCountry.add("SPAIN");
        portsCountry.add("GERMANY");
        portsCountry.add("SEYCHELLES");
        portsCountry.add("JAPAN");
        portsCountry.add("SPAIN");
        portsCountry.add("MALDIVES");
        portsCountry.add("SWEDEN");
        portsCountry.add("BRAZIL");
        portsCountry.add("NICARAGUA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("PHILIPPINES");
        portsCountry.add("COLOMBIA");
        portsCountry.add("GERMANY");
        portsCountry.add("ITALY");
        portsCountry.add("MEXICO");
        portsCountry.add("PANAMA");
        portsCountry.add("MOZAMBIQUE");
        portsCountry.add("VENEZUELA");
        portsCountry.add("FRANCE");
        portsCountry.add("LESOTHO");
        portsCountry.add("ITALY");
        portsCountry.add("MEXICO");
        portsCountry.add("DEMOCARATIC REP OF CONGO");
        portsCountry.add("PERU");
        portsCountry.add("ITALY");
        portsCountry.add("ZAMBIA");
        portsCountry.add("COLOMBIA");
        portsCountry.add("AUSTRALIA");
        portsCountry.add("U.S.A");
        portsCountry.add("MEXICO");
        portsCountry.add("TURKEY");
        portsCountry.add("ITALY");
        portsCountry.add("FRANCE");
        portsCountry.add("MEXICO");
        portsCountry.add("MEXICO");
        portsCountry.add("U.S.A");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("ITALY");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("U.S.A");
        portsCountry.add("U.S.A");
        portsCountry.add("BELARUS");
        portsCountry.add("MALAYSIA");
        portsCountry.add("U.S.A");
        portsCountry.add("ITALY");
        portsCountry.add("JAPAN");
        portsCountry.add("KENYA");
        portsCountry.add("CANADA");
        portsCountry.add("LIBERIA");
        portsCountry.add("JAMAICA");
        portsCountry.add("MEXICO");
        portsCountry.add("URUGUAY");
        portsCountry.add("CANADA");
        portsCountry.add("RUSSIAN FEDERATION");
        portsCountry.add("BRUNEI");
        portsCountry.add("GERMANY");
        portsCountry.add("SPAIN");
        portsCountry.add("OMAN");
        portsCountry.add("JAPAN");
        portsCountry.add("KENYA");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("FRANCE");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("JAPAN");
        portsCountry.add("NEW ZEALAND");
        portsCountry.add("ITALY");
        portsCountry.add("U.S.A");
        portsCountry.add("BAHAMAS");
        portsCountry.add("BRAZIL");
        portsCountry.add("NEW ZEALAND");
        portsCountry.add("GERMANY");
        portsCountry.add("U.S.A");
        portsCountry.add("NEW ZEALAND");
        portsCountry.add("U.S.A");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("NEWIS W.I ");
        portsCountry.add("FRANCE");
        portsCountry.add("JAPAN");
        portsCountry.add("CHINA");
        portsCountry.add("U.S.A");
        portsCountry.add("U.S.A");
        portsCountry.add("SWEDEN");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("MAURITANIA");
        portsCountry.add("ITALY");
        portsCountry.add("MEXICO");
        portsCountry.add("ITALY");
        portsCountry.add("GERMANY");
        portsCountry.add("U.S.A");
        portsCountry.add("DENMARK");
        portsCountry.add("UKRAINE");
        portsCountry.add("GERMANY");
        portsCountry.add("JAPAN");
        portsCountry.add("U.S.A");
        portsCountry.add("GERMANY");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("U.S.A");
        portsCountry.add("ALGERIA");
        portsCountry.add("ARUBA");
        portsCountry.add("SPAIN");
        portsCountry.add("U.S.A");
        portsCountry.add("JAPAN");
        portsCountry.add("NORWAY");
        portsCountry.add("CANADA");
        portsCountry.add("SPAIN");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("GERMANY");
        portsCountry.add("MEXICO");
        portsCountry.add("ITALY");
        portsCountry.add("PERU");
        portsCountry.add("SPAIN");
        portsCountry.add("ITALY");
        portsCountry.add("SPAIN");
        portsCountry.add("SPAIN");
        portsCountry.add("PANAMA");
        portsCountry.add("INDONESIA");
        portsCountry.add("FRENCH POLYNESIA");
        portsCountry.add("SURINAM");
        portsCountry.add("BRAZIL");
        portsCountry.add("FRANCE");
        portsCountry.add("ITALY");
        portsCountry.add("MALAYSIA");
        portsCountry.add("ITALY");
        portsCountry.add("MALAYSIA");
        portsCountry.add("COLOMBIA");
        portsCountry.add("ITALY");
        portsCountry.add("ITALY");
        portsCountry.add("ITALY");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("U.S.A");
        portsCountry.add("ST MARTEN");
        portsCountry.add("CAMBODIA");
        portsCountry.add("U.S.A");
        portsCountry.add("ITALY");
        portsCountry.add("GREECE");
        portsCountry.add("ITALY");
        portsCountry.add("PERU");
        portsCountry.add("ITALY");
        portsCountry.add("U.S.A");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("MONTSERRAT");
        portsCountry.add("TRINIDAD ");
        portsCountry.add("CONGO");
        portsCountry.add("GUADELOUPE");
        portsCountry.add("PORTUGAL");
        portsCountry.add("SPAIN");
        portsCountry.add("ITALY");
        portsCountry.add("HAITI");
        portsCountry.add("NEW ZEALAND");
        portsCountry.add("SOUTH AFRICA");
        portsCountry.add("NIGERIA");
        portsCountry.add("MALAYSIA");
        portsCountry.add("MAURITIUS");
        portsCountry.add("PAPUA NEW GUINEA");
        portsCountry.add("TRINIDAD ");
        portsCountry.add("EGYPT");
        portsCountry.add("SUDAN");
        portsCountry.add("U.S.A");
        portsCountry.add("PORTUGAL");
        portsCountry.add("BRAZIL");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("CZECH REPUBLIC");
        portsCountry.add("ITALY");
        portsCountry.add("CANARY ISLANDS");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("MEXICO");
        portsCountry.add("MEXICO");
        portsCountry.add("VENEZUELA");
        portsCountry.add("HONDURAS");
        portsCountry.add("CANARY ISLANDS");
        portsCountry.add("COSTA RICA");
        portsCountry.add("MEXICO");
        portsCountry.add("GUATEMALA");
        portsCountry.add("EL SALVADOR");
        portsCountry.add("MEXICO");
        portsCountry.add("CHILE");
        portsCountry.add("CHINA");
        portsCountry.add("CANADA");
        portsCountry.add("MEXICO");
        portsCountry.add("ECUADOR");
        portsCountry.add("U.S.A");
        portsCountry.add("ITALY");
        portsCountry.add("BRAZIL");
        portsCountry.add("GERMANY");
        portsCountry.add("ITALY");
        portsCountry.add("ITALY");
        portsCountry.add("CANADA");
        portsCountry.add("REUNION");
        portsCountry.add("ICELAND");
        portsCountry.add("MEXICO");
        portsCountry.add("GERMANY");
        portsCountry.add("U.S.A");
        portsCountry.add("GERMANY");
        portsCountry.add("LATVIA");
        portsCountry.add("CROATIA");
        portsCountry.add("BRAZIL");
        portsCountry.add("BRAZIL");
        portsCountry.add("DOMINICAN  REPBLIC");
        portsCountry.add("SAUDI ARABIA");
        portsCountry.add("TORTOLA");
        portsCountry.add("ITALY");
        portsCountry.add("CHINA");
        portsCountry.add("DOMINICAN  REPBLIC");
        portsCountry.add("GERMANY");
        portsCountry.add("NETHERLANDS");
        portsCountry.add("ITALY");
        portsCountry.add("GERMANY");
        portsCountry.add("JAPAN");
        portsCountry.add("JAPAN");
        portsCountry.add("SPAIN");
        portsCountry.add("PERU");
        portsCountry.add("ITALY");
        portsCountry.add("MEXICO");
        portsCountry.add("U.S.A");
        portsCountry.add("BRAZIL");
        portsCountry.add("AUSTRIA");
        portsCountry.add("CHILE");
        portsCountry.add("U.S.A");
        portsCountry.add("U.S.A");
        portsCountry.add("U.S.A");
        portsCountry.add("COSTA RICA");
        portsCountry.add("PUERTO RICO");
        portsCountry.add("MEXICO");
        portsCountry.add("PORTUGAL");
        portsCountry.add("HONDURAS");
        portsCountry.add("EL SALVADOR");
        portsCountry.add("SPAIN");
        portsCountry.add("CHINA");
        portsCountry.add("PORTUGAL");
        portsCountry.add("COLOMBIA");
        portsCountry.add("BOLIVIA");
        portsCountry.add("CANARY ISLANDS");
        portsCountry.add("CANARY ISLANDS");
        portsCountry.add("SPAIN");
        portsCountry.add("CHILE");
        portsCountry.add("SPAIN");
        portsCountry.add("DOMINICAN  REPBLIC");
        portsCountry.add("GUATEMALA");
        portsCountry.add("BRAZIL");
        portsCountry.add("BRAZIL");
        portsCountry.add("BOSNIA ");
        portsCountry.add("CANADA");
        portsCountry.add("ITALY");
        portsCountry.add("U.S.A");
        portsCountry.add("ITALY");
        portsCountry.add("GERMANY");
        portsCountry.add("U.S.A");
        portsCountry.add("INDONESIA");
        portsCountry.add("SOUTH KOREA");
        portsCountry.add("SPAIN");
        portsCountry.add("TUNIS");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("UAE");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("JAPAN");
        portsCountry.add("U.S.A");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("MALAYSIA");
        portsCountry.add("ITALY");
        portsCountry.add("CAMBODIA");
        portsCountry.add("SINGAPORE");
        portsCountry.add("ITALY");
        portsCountry.add("EGYPT");
        portsCountry.add("MACEONIA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("BULGARIA");
        portsCountry.add("INDONESIA");
        portsCountry.add("ITALY");
        portsCountry.add("SPAIN");
        portsCountry.add("TUNIS");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("U.S.A");
        portsCountry.add("ST BARTHOLOME");
        portsCountry.add("PORTUGAL");
        portsCountry.add("GRENADA");
        portsCountry.add("CANADA");
        portsCountry.add("U.S.A");
        portsCountry.add("ANTIGUA");
        portsCountry.add("RUSSIAN FEDERATION");
        portsCountry.add("VIRGIN ISLANDS U.S.");
        portsCountry.add("NORWAY");
        portsCountry.add("SWEDEN");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("FRANCE");
        portsCountry.add("GERMANY");
        portsCountry.add("BRAZIL");
        portsCountry.add("EGYPT");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("INDONESIA");
        portsCountry.add("FIJI");
        portsCountry.add("CHINA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("AUSTRALIA");
        portsCountry.add("CHINA");
        portsCountry.add("TAIWAN");
        portsCountry.add("CHINA");
        portsCountry.add("JAPAN");
        portsCountry.add("GHANA");
        portsCountry.add("CHILE");
        portsCountry.add("ESTONIA");
        portsCountry.add("MADAGASCAR");
        portsCountry.add("U.S.A");
        portsCountry.add("MEXICO");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("MOROCCO");
        portsCountry.add("ITALY");
        portsCountry.add("NEW ZEALAND");
        portsCountry.add("MALAYSIA");
        portsCountry.add("HONDURAS");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("GHANA");
        portsCountry.add("SPAIN");
        portsCountry.add("EGYPT");
        portsCountry.add("ITALY");
        portsCountry.add("PORTUGAL");
        portsCountry.add("ITALY");
        portsCountry.add("SPAIN");
        portsCountry.add("GREECE");
        portsCountry.add("CANADA");
        portsCountry.add("CHINA");
        portsCountry.add("NEW ZEALAND");
        portsCountry.add("MADAGASCAR");
        portsCountry.add("JAPAN");
        portsCountry.add("JAPAN");
        portsCountry.add("U.S.A");
        portsCountry.add("SPAIN");
        portsCountry.add("MEXICO");
        portsCountry.add("JAPAN");
        portsCountry.add("ITALY");
        portsCountry.add("CANADA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("MEXICO");
        portsCountry.add("FRANCE");
        portsCountry.add("JAPAN");
        portsCountry.add("ITALY");
        portsCountry.add("ITALY");
        portsCountry.add("GERMANY");
        portsCountry.add("ITALY");
        portsCountry.add("LIBYA");
        portsCountry.add("NORWAY");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("JAPAN");
        portsCountry.add("U.S.A");
        portsCountry.add("U.S.A");
        portsCountry.add("PERU");
        portsCountry.add("TUNIS");
        portsCountry.add("TUNESIA");
        portsCountry.add("FINLAND");
        portsCountry.add("TURKEY");
        portsCountry.add("ITALY");
        portsCountry.add("GERMANY");
        portsCountry.add("SPAIN");
        portsCountry.add("SPAIN");
        portsCountry.add("CHILE");
        portsCountry.add("CANADA");
        portsCountry.add("ITALY");
        portsCountry.add("ITALY");
        portsCountry.add("ITALY");
        portsCountry.add("MEXICO");
        portsCountry.add("ITALY");
        portsCountry.add("ITALY");
        portsCountry.add("ITALY");
        portsCountry.add("BRAZIL");
        portsCountry.add("CANADA");
        portsCountry.add("AUSTRIA");
        portsCountry.add("SPAIN");
        portsCountry.add("SWITZERLAND");
        portsCountry.add("GERMANY");
        portsCountry.add("LITHUANIA");
        portsCountry.add("ITALY");
        portsCountry.add("SPAIN");
        portsCountry.add("VIETNAM");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("NAMIBIA ");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("POLAND");
        portsCountry.add("U.S.A");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("NEW ZEALAND");
        portsCountry.add("CHINA");
        portsCountry.add("U.S.A");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("ANTILLES");
        portsCountry.add("U.S.A");
        portsCountry.add("NAMIBIA ");
        portsCountry.add("CANADA");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("GERMANY");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("MYANMAR");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("JAPAN");
        portsCountry.add("UNITED KINGDOM");
        portsCountry.add("CHINA");
        portsCountry.add("CROATIA");
        portsCountry.add("PHILIPPINES");
        portsCountry.add("SPAIN");
        portsCountry.add("SPAIN");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("CHINA");
        portsCountry.add("SWITZERLAND");

        return portsCountry;
    }
}
